### ISSUE TITLE
what is the minimum EKS version supported?

### ISSUE THREAD

**Issue by gamer-deravanesian** [snyk/leaky-vessels-dynamic-detector#13]
I am getting bellow error while trying to install it on EKS:

`[ebpf-detector] 2024/02/08 17:38:18 logger.go:49: "msg"="Failed loading chdir bpf objects" "error"="field TraceChdir: program trace_chdir: map events: map create: invalid argument (without BTF k/v)"`

**Comment by nozik** [comment]
Hi @gamer-deravanesian, please share the linux distro of your Kubernetes nodes. Thanks

**Comment by gamer-deravanesian** [comment]
OS (Architecture): linux (amd64)
OS image: Amazon Linux 2
Kernel version: 5.4.188-104.359.amzn2.x86_64
Kubelet version: v1.22.6-eks-7d68063

**Comment by nipunsahnieptura** [comment]
@gamer-deravanesian  @nozik  - Please suggest how we should proceed in resolving this. this impacts our production clusters?

**Comment by nozik** [comment]
@gamer-deravanesian @nipunsahni1981 We've tested successfully in later versions of Amazon Linux. If possible, please upgrade the Kubernetes node. Alternatively, you can reach out to AWS support and ask them about BTF support in the Amazon Linux 2 version that you're using.

**Comment by nozik** [comment]
@gamer-deravanesian @nipunsahni1981 According to AWS, the minimal EKS version that support eBPF is 1.25. Updating the docs
